#!/bin/sh



echo "Signing ..."
ldid -s /var/jb/usr/local/libexec/xpcToolStrapd /var/jb/Library/MobileSubstrate/DynamicLibraries/xpcToolStrapApps.dylib
ldid -s /var/jb/usr/local/libexec/xpcToolStrapd /var/jb/Library/MobileSubstrate/DynamicLibraries/xpcToolStrapSB.dylib